### PR TITLE
Fix NaN values when typing in width/height of Snapshot

### LINKED ISSUE #453: Text fields for controlling snapshots are not working properly
In snapshots, when you delete “Width”, then the “Left” field become blank. Similarly, when you delete “Height”, “Top” become blank. When either of the field become blank this way, the selection frame disappears. It can be reset by clicking “set frame to maximum/viewport". See video:

https://github.com/Kitware/UPennContrast/assets/13998824/57e003c9-b667-40c1-a7cf-dc7cec8951d7

### PR DESCRIPTION
**Pull request by bruyeret**
Close #453

### CODE REVIEW

File: src/components/Snapshots.vue [hunk 1]
```diff
@@ -446,16 +446,20 @@ export default class Snapshots extends Vue {
...
   }
 
   get bboxHeight(): number {
     return (this.bboxBottom || 0) - (this.bboxTop || 0);
   }
 
-  set bboxHeight(value: number) {
-    this.bboxBottom = (this.bboxTop || 0) + parseInt("" + value, 0);
+  set bboxHeight(value: string) {
+    const parsedValue = parseInt("0" + value, 10);
```
Comment (luciemac) [inline src/components/Snapshots.vue:460]: Can you factorize this part, please?

Comment (bruyeret) [reply src/components/Snapshots.vue]: Of course!

**Comment by arjunrajlab** [comment]
Looks good to me1

File: src/components/Snapshots.vue [hunk 2]
```diff
@@ -349,6 +349,11 @@ interface IDownloadParameters {
   tiffCompression?: string;
 }
 
+function intFromString(value: string) {
```
Comment (luciemac) [inline src/components/Snapshots.vue:352]: LGTM.
In my opinion, it would be great to have a math helper file with such functions, WDYT?

**Comment by luciemac** [comment]
LGTM

File: src/components/Snapshots.vue (hunk 2 above)
Comment (bruyeret) [reply src/components/Snapshots.vue:352]: After more thoughts, this function shouldn't be as is in a math helper file, because it makes the assumption that "not a number" should be treated as zero
