### PR TITLE
Reformat annotation tooltips, fix unrolling

### LINKED ISSUE #332: Annotation tooltip improvement
For annotations, it would be nice for the tooltips to show the following information:
Tags, annotation ID (so people know where it is in the list, much requested feature!), and selected properties. Perhaps these can be properties that are included in the list for now, although perhaps the user would want to customize further in future.

Current tooltip (image below) shows coordinates, which are already known from the navigator, so it is currently a bit redundant.

image

### PR DESCRIPTION
**Pull request by bruyeret**
IndexXY, IndexZ, IndexT, IndexC can be undefined

Closes #332

### CODE REVIEW

File: src/components/AnnotationViewer.vue [hunk 1]
```diff
@@ -43,6 +44,27 @@ export default class AnnotationViewer extends Vue {
...
+    for (const annotation of this.annotationStore.annotations) {
+      const centroid = this.annotationStore.annotationCentroids[annotation.id];
+      const unrolledCentroid = this.unrolledCoordinates(
+        [centroid],
+        annotation.location,
+        anyImage
+      )[0];
+      centroids[annotation.id] = unrolledCentroid;
+    }
+    return centroids;
```
Comment (luciemac) [inline src/components/AnnotationViewer.vue:65]:
```
const anyImage = this.store.dataset?.anyImage();
if (anyImage) {
  for (const annotation of this.annotationStore.annotations) {
    const centroid = this.annotationStore.annotationCentroids[annotation.id];
    const unrolledCentroid = this.unrolledCoordinates(
      [centroid],
      annotation.location,
      anyImage
    )[0];
    centroids[annotation.id] = unrolledCentroid;
  }
}
return centroids;
```

Comment (bruyeret) [reply src/components/AnnotationViewer.vue:66]: Thanks, I forced push a commit to take your idea into account

**Comment by luciemac** [comment]
LGTM
